import Link from "next/link";
import LegalDocument from "@/components/LegalDocument";

export const metadata = {
  title: "Privacy Policy · Faraday Daily Challenge",
  description:
    "How Faraday Intelligence LLC collects and uses information on the Faraday Daily Challenge.",
};

// Privacy Policy — static content, verbatim per CC-DC-LEGAL-1.0. Sibling of
// /terms; the old combined /legal placeholder redirects to /terms.

export default function PrivacyPage() {
  return (
    <LegalDocument
      title="Faraday Daily Challenge — Privacy Policy"
      effectiveDate="July 30, 2026"
      sibling={{ label: "Terms of Service", href: "/terms" }}
    >
      <p>
        This Privacy Policy describes how <strong>Faraday Intelligence LLC</strong>, a Minnesota
        limited liability company (&ldquo;Faraday,&rdquo; &ldquo;we,&rdquo; &ldquo;us&rdquo;),
        collects and uses information when you use the Faraday Daily Challenge&trade; at
        www.faradaydailychallenge.com and faraday-intelligence.ai (the &ldquo;Service&rdquo;).
      </p>

      <h2>1. Information we collect</h2>
      <p>
        <strong>Information you provide.</strong> When you register, we collect your email address.
        You may also provide a display name, team membership, an organization tag, and anything you
        send through the <Link href="/help/feedback">Feedback page</Link>.
      </p>
      <p>
        <strong>Information generated by your use of the Service.</strong> We record your puzzle
        activity &mdash; completions, guesses, scores, solve times, streaks, season and team
        participation, and leaderboard placement &mdash; associated with your account.
      </p>
      <p>
        <strong>Technical information.</strong> Like most websites, our hosting and infrastructure
        providers automatically log standard technical data such as IP address, browser type, device
        information, and pages requested, used for security, debugging, and operating the Service.
        We use essential cookies and similar storage needed to keep you signed in and to run the
        Service; we do not use third-party advertising cookies.
      </p>

      <h2>2. How we use information</h2>
      <p>We use the information above to:</p>
      <ul>
        <li>
          Operate the Service: authenticate you by magic link, save your progress, compute scores
          and streaks, and run leaderboards, teams, and seasons;
        </li>
        <li>
          Display gameplay information: your display name, scores, streaks, and team/organization
          affiliation may be visible to other users on leaderboards and team pages;
        </li>
        <li>
          Communicate with you about the Service, including sign-in links and service announcements;
        </li>
        <li>
          <strong>
            Tell you about related Faraday Intelligence LLC products and offerings, including
            Jurisdiction Watch&trade;.
          </strong>{" "}
          Every marketing email includes an unsubscribe mechanism, and opting out of marketing does
          not affect sign-in or service emails;
        </li>
        <li>
          Maintain security, prevent abuse and leaderboard manipulation, and comply with legal
          obligations;
        </li>
        <li>
          Understand aggregate usage to improve puzzles and features. Aggregated or de-identified
          statistics (for example, &ldquo;X% of players solved today&rsquo;s Rackl in one
          guess&rdquo;) may be published and are not personal information.
        </li>
      </ul>

      <h2>3. What we do not do</h2>
      <p>
        We do not sell your personal information. We do not share it with third parties for their
        own advertising. We do not use third-party ad networks on the Service.
      </p>

      <h2>4. Service providers</h2>
      <p>
        We use infrastructure providers to run the Service &mdash; including hosting,
        database/authentication, and email-delivery providers &mdash; who process information on our
        behalf under their own contractual obligations, solely to provide their services to us.
      </p>

      <h2>5. Data retention</h2>
      <p>
        We keep account and gameplay data while your account is active. Historical scores and
        completions are retained to maintain leaderboard and season integrity. You may request
        deletion of your account and associated personal information through the{" "}
        <Link href="/help/feedback">Feedback page</Link>; we will action verified requests within a
        reasonable period, except where retention is required for legal, security, or
        fraud-prevention purposes. Aggregate statistics that no longer identify you may be retained.
      </p>

      <h2>6. Your choices and rights</h2>
      <ul>
        <li>
          <strong>Marketing:</strong> unsubscribe via the link in any marketing email.
        </li>
        <li>
          <strong>Display name:</strong> you control the name shown on leaderboards.
        </li>
        <li>
          <strong>Access, correction, deletion:</strong> request these through the{" "}
          <Link href="/help/feedback">Feedback page</Link>. Depending on where you live, you may
          have additional rights under applicable privacy laws; we will honor valid requests as
          required by law.
        </li>
      </ul>

      <h2>7. Children</h2>
      <p>
        The Service is not directed to children under 16, and we do not knowingly collect personal
        information from them. If you believe a child under 16 has registered, contact us through
        the <Link href="/help/feedback">Feedback page</Link> and we will delete the account.
      </p>

      <h2>8. Security</h2>
      <p>
        We use commercially reasonable technical and organizational measures to protect information,
        including access controls on our databases. No system is perfectly secure; use of the
        Service is at your own risk to the extent permitted by law.
      </p>

      <h2>9. International users</h2>
      <p>
        The Service is operated from the United States and information is processed in the United
        States. If you use the Service from outside the U.S., you understand your information will
        be transferred to and processed in the U.S.
      </p>

      <h2>10. Changes to this policy</h2>
      <p>
        We may update this Privacy Policy; the current version will always be posted at{" "}
        <Link href="/privacy">/privacy</Link> with its effective date. Material changes will be
        indicated by updating the effective date.
      </p>

      <h2>11. Contact</h2>
      <p>
        Privacy questions and requests can be sent through the{" "}
        <Link href="/help/feedback">Feedback page</Link> on the Service.
      </p>
    </LegalDocument>
  );
}
